<?php

namespace App\Models;

use App\Helpers\Utils;
use CodeIgniter\Model;

class ClientgroupModel extends Model
{
    protected $DBGroup          = 'default';
    protected $table            = 'clientgroups';
    protected $primaryKey       = 'id';
    protected $useAutoIncrement = false;
    protected $insertID         = 0;
    protected $useSoftDeletes   = true;
    protected $protectFields    = false;

    protected $useTimestamps = true;

    public function insert($data = null, bool $returnID = true)
    {
        $data['id'] =  Utils::generateRandomUUID();
        return parent::insert($data, $returnID); // TODO: Change the autogenerated stub
    }
}
